using Microsoft.EntityFrameworkCore;using NetGuardGT.Api.Data;using NetGuardGT.Api.DTOs;using NetGuardGT.Api.Enums;using NetGuardGT.Api.Models;using NetGuardGT.Api.Services;
namespace NetGuardGT.Tests;
public class IncidenteServiceTests{
 private static AppDbContext Db(){var o=new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;return new AppDbContext(o);} 
 private static async Task<(AppDbContext db,IncidenteService svc,Tecnico tec)> Base(){var db=Db();db.SitiosRed.Add(new SitioRed{Id=1,Nombre="POP",Ubicacion="Jalapa"});var t=new Tecnico{Id=1,NombreCompleto="Ana",Correo="ana@x.com",Telefono="1"};t.Especialidades.Add(new TecnicoEspecialidad{Especialidad=EspecialidadTecnica.FibraOptica});db.Tecnicos.Add(t);await db.SaveChangesAsync();return(db,new IncidenteService(db),t);} 
 [Fact]public async Task Crear_CalculaSlaCritico(){var x=await Base();var i=await x.svc.CrearAsync(new("Falla","Desc",TipoIncidente.FibraOptica,SeveridadIncidente.Critica,1),"coord");Assert.Equal(4,(i.FechaLimiteSla-i.FechaRegistro).TotalHours);} 
 [Fact]public async Task Asignar_RechazaEspecialidadIncorrecta(){var x=await Base();var i=await x.svc.CrearAsync(new("Falla","Desc",TipoIncidente.Microondas,SeveridadIncidente.Alta,1),"c");var r=await x.svc.AsignarAsync(i.Id,new(x.tec.Id,"c"));Assert.False(r.ok);} 
 [Fact]public async Task Asignar_MaximoTresActivos(){var x=await Base();for(int n=0;n<3;n++){var i=await x.svc.CrearAsync(new($"F{n}","D",TipoIncidente.FibraOptica,SeveridadIncidente.Alta,1),"c");Assert.True((await x.svc.AsignarAsync(i.Id,new(1,"c"))).ok);}var cuarto=await x.svc.CrearAsync(new("F4","D",TipoIncidente.FibraOptica,SeveridadIncidente.Alta,1),"c");Assert.False((await x.svc.AsignarAsync(cuarto.Id,new(1,"c"))).ok);} 
 [Fact]public async Task Estados_AvanzanEnOrden(){var x=await Base();var i=await x.svc.CrearAsync(new("F","D",TipoIncidente.FibraOptica,SeveridadIncidente.Alta,1),"c");Assert.True((await x.svc.AsignarAsync(i.Id,new(1,"c"))).ok);Assert.True((await x.svc.IniciarAsync(i.Id,new("t"))).ok);Assert.True((await x.svc.ResolverAsync(i.Id,new("sol","t"))).ok);Assert.True((await x.svc.CerrarAsync(i.Id,new("ok","c"))).ok);} 
 [Fact]public async Task NoPuedeResolverRegistrado(){var x=await Base();var i=await x.svc.CrearAsync(new("F","D",TipoIncidente.FibraOptica,SeveridadIncidente.Alta,1),"c");Assert.False((await x.svc.ResolverAsync(i.Id,new("sol","t"))).ok);} 
 [Fact]public async Task Liberar_RegresaARegistrado(){var x=await Base();var i=await x.svc.CrearAsync(new("F","D",TipoIncidente.FibraOptica,SeveridadIncidente.Alta,1),"c");await x.svc.AsignarAsync(i.Id,new(1,"c"));Assert.True((await x.svc.LiberarAsync(i.Id,new("No puedo","t"))).ok);Assert.Equal(EstadoIncidente.Registrado,i.Estado);Assert.Null(i.TecnicoAsignadoId);} 
 [Fact]public async Task EscalaCriticoDespuesDeDosHoras(){var x=await Base();var i=await x.svc.CrearAsync(new("F","D",TipoIncidente.FibraOptica,SeveridadIncidente.Critica,1),"c");i.FechaRegistro=DateTime.UtcNow.AddHours(-3);await x.db.SaveChangesAsync();Assert.Equal(1,await x.svc.EscalarPendientesAsync());Assert.True(i.Escalado);} 
 [Fact]public async Task Historial_SeCreaAlRegistrar(){var x=await Base();var i=await x.svc.CrearAsync(new("F","D",TipoIncidente.FibraOptica,SeveridadIncidente.Alta,1),"c");Assert.Single(await x.db.HistorialIncidentes.Where(h=>h.IncidenteId==i.Id).ToListAsync());}
}
