// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetGuardGT.Api.Data;

#nullable disable

namespace NetGuardGT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613161621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("NetGuardGT.Api.Models.HistorialIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.ToTable("HistorialIncidentes");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Escalado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEscalamiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaLimiteSla")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SitioRedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolucionAplicada")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SitioRedId");

                    b.HasIndex("TecnicoAsignadoId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.SitioRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SitiosRed");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.TecnicoEspecialidad", b =>
                {
                    b.Property<int>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Especialidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("TecnicoId", "Especialidad");

                    b.ToTable("TecnicoEspecialidades");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.HistorialIncidente", b =>
                {
                    b.HasOne("NetGuardGT.Api.Models.Incidente", "Incidente")
                        .WithMany("Historial")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Incidente", b =>
                {
                    b.HasOne("NetGuardGT.Api.Models.SitioRed", "SitioRed")
                        .WithMany("Incidentes")
                        .HasForeignKey("SitioRedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetGuardGT.Api.Models.Tecnico", "TecnicoAsignado")
                        .WithMany("IncidentesAsignados")
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SitioRed");

                    b.Navigation("TecnicoAsignado");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.TecnicoEspecialidad", b =>
                {
                    b.HasOne("NetGuardGT.Api.Models.Tecnico", "Tecnico")
                        .WithMany("Especialidades")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Incidente", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.SitioRed", b =>
                {
                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Tecnico", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("IncidentesAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
